src/Entity/DownloadRequest.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DownloadRequestRepository")
 */
class DownloadRequest
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $MiddleName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $LastName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Phone;

    /**
     * @ORM\Column(type="text")
     */
    private $Reason;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Dataset", inversedBy="downloadRequests")
     */
    private $Dataset;

    /**
     * @ORM\Column(type="json_array", nullable=true)
     */
    private $Attachment = [];

    /**
     * @ORM\Column(type="datetime")
     */
    private $RequestedDate;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $ApprovedDate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Token;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $count;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $Status;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $File;
  
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $restrictionFile;


    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $approver1;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $approver2;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $approver3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $affliation;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DownloadRequestApprover", mappedBy="request")
     */
    private $downloadRequestApprovers;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\FosUser", inversedBy="downloadRequests")
     */
    private $internalRequester;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $objective;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $rejectionMessage;

    public function __construct()
    {
        $this->downloadRequestApprovers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getMiddleName(): ?string
    {
        return $this->MiddleName;
    }

    public function setMiddleName(string $MiddleName): self
    {
        $this->MiddleName = $MiddleName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->Phone;
    }

    public function setPhone(string $Phone): self
    {
        $this->Phone = $Phone;

        return $this;
    }

    public function getReason(): ?string
    {
        return $this->Reason;
    }

    public function setReason(string $Reason): self
    {
        $this->Reason = $Reason;

        return $this;
    }

    public function getDataset(): ?Dataset
    {
        return $this->Dataset;
    }

    public function setDataset(?Dataset $Dataset): self
    {
        $this->Dataset = $Dataset;

        return $this;
    }

    public function getAttachment(): ?array
    {
        return $this->Attachment;
    }

    public function setAttachment(array $Attachment): self
    {
        $this->Attachment = $Attachment;

        return $this;
    }

    public function getRequestedDate(): ?\DateTimeInterface
    {
        return $this->RequestedDate;
    }

    public function setRequestedDate(\DateTimeInterface $RequestedDate): self
    {
        $this->RequestedDate = $RequestedDate;

        return $this;
    }

    public function getApprovedDate(): ?\DateTimeInterface
    {
        return $this->ApprovedDate;
    }

    public function setApprovedDate(\DateTimeInterface $ApprovedDate): self
    {
        $this->ApprovedDate = $ApprovedDate;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->Token;
    }

    public function setToken(string $Token): self
    {
        $this->Token = $Token;

        return $this;
    }

    public function getCount(): ?int
    {
        return $this->count;
    }

    public function setCount(int $count): self
    {
        $this->count = $count;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->Status;
    }

    public function setStatus(bool $Status): self
    {
        $this->Status = $Status;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->File;
    }

    public function setFile(string $File): self
    {
        $this->File = $File;

        return $this;
    }


    public function getRestrictionFile(): ?string
    {
        return $this->restrictionFile;
    }

    public function setRestrictionFile(string $restrictionFile): self
    {
        $this->restrictionFile = $restrictionFile;

        return $this;
    }

    public function getApprover1(): ?int
    {
        return $this->approver1;
    }

    public function setApprover1(?int $approver1): self
    {
        $this->approver1 = $approver1;

        return $this;
    }

    public function getApprover2(): ?int
    {
        return $this->approver2;
    }

    public function setApprover2(?int $approver2): self
    {
        $this->approver2 = $approver2;

        return $this;
    }

    public function getApprover3(): ?int
    {
        return $this->approver3;
    }

    public function setApprover3(?int $approver3): self
    {
        $this->approver3 = $approver3;

        return $this;
    }

    public function getAffliation(): ?string
    {
        return $this->affliation;
    }

    public function setAffliation(?string $affliation): self
    {
        $this->affliation = $affliation;

        return $this;
    }

    /**
     * @return Collection|DownloadRequestApprover[]
     */
    public function getDownloadRequestApprovers(): Collection
    {
        return $this->downloadRequestApprovers;
    }

    public function addDownloadRequestApprover(DownloadRequestApprover $downloadRequestApprover): self
    {
        if (!$this->downloadRequestApprovers->contains($downloadRequestApprover)) {
            $this->downloadRequestApprovers[] = $downloadRequestApprover;
            $downloadRequestApprover->setRequest($this);
        }

        return $this;
    }

    public function removeDownloadRequestApprover(DownloadRequestApprover $downloadRequestApprover): self
    {
        if ($this->downloadRequestApprovers->contains($downloadRequestApprover)) {
            $this->downloadRequestApprovers->removeElement($downloadRequestApprover);
            // set the owning side to null (unless already changed)
            if ($downloadRequestApprover->getRequest() === $this) {
                $downloadRequestApprover->setRequest(null);
            }
        }

        return $this;
    }

    public function getInternalRequester(): ?FosUser
    {
        return $this->internalRequester;
    }

    public function setInternalRequester(?FosUser $internalRequester): self
    {
        $this->internalRequester = $internalRequester;

        return $this;
    }

    public function getObjective(): ?string
    {
        return $this->objective;
    }

    public function setObjective(?string $objective): self
    {
        $this->objective = $objective;

        return $this;
    }

    public function getRejectionMessage(): ?string
    {
        return $this->rejectionMessage;
    }

    public function setRejectionMessage(?string $rejectionMessage): self
    {
        $this->rejectionMessage = $rejectionMessage;

        return $this;
    }
}

src/Form/DownloadRequestType.php
<?php

namespace App\Form;

use App\Entity\DownloadRequest;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DownloadRequestType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name')
            ->add('MiddleName')
            ->add('LastName')
            ->add('Email')
            ->add('Phone')
            ->add('Reason')
            ->add('Attachment')
            ->add('RequestedDate')
            ->add('ApprovedDate')
            ->add('Token')
            ->add('count')
            ->add('Status')
            ->add('File')
            ->add('Dataset')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => DownloadRequest::class,
        ]);
    }
}

templates/download_request/_delete_form.html.twig
<form method="post" action="{{ path('download_request_delete', {'id': download_request.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ download_request.id) }}">
    <button class="btn">Delete</button>
</form>

templates/download_request/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/download_request/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit DownloadRequest{% endblock %}

{% block body %}
    <h1>Edit DownloadRequest</h1>

    {{ include('download_request/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('download_request_index') }}">back to list</a>

    {{ include('download_request/_delete_form.html.twig') }}
{% endblock %}

templates/download_request/index.html.twig
{% extends 'base.html.twig' %}
{% block pageheader %}
	<h2> Approval requests</h2>
{% endblock %}

{% block body %}


</tbody>
</table>

<div class="table-responsive">
			 <table class="table table-bordered table-condensed">
				<thead>
					<tr>
						<th>#</th>
						<th>FullNames</th>
						<th>Email</th>

						<th>Reason</th>
						<th>Restricted</th>
						<th>Research Proposal</th>
						<th>RequestedDate</th>
						<th>Directorate</th>
						<th>NDMC</th>
						<th>Department</th>
						<th>actions</th>
					</tr>
				</thead>
				<tbody>
					{% set id = 1 %}
					{% for download_request in download_requests %}
						<tr style="vertical-align:middle">
							<td  rowspan="2">{{ id }}
								{% set id = id+1  %}</td>
							<td rowspan="2">{{ download_request.Name }}
								{{ download_request.MiddleName }}
								{{ download_request.LastName }}</td>
							<td rowspan="2">{{ download_request.Email }}</td>

							<td rowspan="2">{{ download_request.Reason }}</td>

							<td rowspan="2">
								{% if download_request.dataset.isRestricted %}
									<p class="badge badge-danger">Yes</p>
									<p>
										<form method="post" class="inline" action="{{ path('download_restriction') }}" class="form-inline">
											<input name="restriction" value="{{ download_request.id}}" hidden/>
											<button class="btn btn-sm btn-success inline" type="submit">
												<i class="fa fa-download"></i>
												download</button>


										</form>

									</p>

								{% else %}
									<span class="badge badge-success">Not Restricted</span>
								{% endif %}

							</td>

							<td rowspan="2">
								{% if download_request.file %}

									<p>
										<form method="post" class="inline" action="{{ path('download_legitimacy') }}" class="form-inline">
											<input name="legitimacy" value="{{ download_request.id}}" hidden/>
											<button class="btn btn-sm btn-success inline" type="submit">
												<i class="fa fa-download"></i>
												download</button>


										</form>

									</p>


								{% endif %}

							</td>

							<td rowspan="2">{{ download_request.RequestedDate ? download_request.RequestedDate|date('Y-m-d') : '' }}</td>


							{% set  stat="" %}
							{% set  messg="" %}

							{% if download_request.approver1 == 11 or download_request.approver1 == 21 %}


								{% set messg="Approved" %}
								{% set stat="success" %}

							{% elseif download_request.approver1 is null  %}


								{% set messg="Pending" %}
								{% set stat="warning" %}

							{% else %}

								{% set messg="Rejected" %}
								{% set stat="danger" %}
							{% endif %}
							<td>
								<span class="label label-{{ stat }}"><i class="fa fa-arrow-right"></i> {{messg }}</span>
							</td>


							{% if download_request.approver2 ==11 or download_request.approver2 ==21 %}


								{% set messg="Approved" %}
								{% set stat="success" %}

							{% elseif download_request.approver2 is null  %}


								{% set messg="Pending" %}
								{% set stat="warning" %}

							{% else %}

								{% set messg="Rejected" %}
								{% set stat="danger" %}
							{% endif %}
							<td>
								<span class="label label-{{ stat }}"><i class="fa fa-arrow-right"></i>{{messg }}</span>
							</td>


							{% if download_request.approver3 == 11  or download_request.approver3 == 21 %}


								{% set messg="Approved" %}
								{% set stat="success" %}

							{% elseif download_request.approver3 is null  %}


								{% set messg="Pending" %}
								{% set stat="warning" %}

							{% else %}

								{% set messg="Rejected" %}
								{% set stat="danger" %}
							{% endif %}
							<td rowspan="2">
								<span class="label label-{{ stat }}"> {{messg }} <i style=" transform: rotate(180deg);" class="fa fa-share"></i></span>
							</td>


							<td rowspan="2">
								{% if is_allowed(app.user,'approver1') or is_allowed(app.user,'approver2') or is_allowed(app.user,'approver3') %}

									<a class="btn btn-sm btn-success" href="{{ path('download_request_show', {'id': download_request.id}) }}">Detail</a>


								{% endif %}
							</td>
						</tr>

						{% set stat = "default" %}

    <tr>



					{% if download_request.approver1 == 21 %}



								{% set messg="Approved" %}
								{% set stat="success" %}

							{# {% elseif download_request.approver1 == 0  %}

							{% set messg="Rejected" %}
								{% set stat="danger" %} #}

							{% elseif download_request.approver1 is null or  download_request.approver1 == 11  %}


								{% set messg="Pending" %}
								{% set stat="warning" %}

							{% else %}

								{% set messg="Rejected" %}
								{% set stat="danger" %}
							{% endif %}
    <td><span class="label label-{{ stat }}"> {{messg }} <i  class="fa fa-arrow-left"></i></span></td>

{% if download_request.approver2 == 21 %}


								{% set messg="Approved" %}
								{% set stat="success" %}

							{# {% elseif download_request.approver2 is null  %} #}
							{% elseif download_request.approver2 is null or  download_request.approver2 == 11  %}



								{% set messg="Pending" %}
								{% set stat="warning" %}

							{% else %}

								{% set messg="Rejected" %}
								{% set stat="danger" %}
							{% endif %}
     <td><span class="label label-{{ stat }}"> {{messg }} <i  class="fa fa-arrow-left"></i></span></td>


  </tr>
					{% else %}
						<tr>
							<td colspan="15">no records found</td>
						</tr>
	{% endfor %}
				</tbody>
			</table>
		<div class="pull-right">
				{{ knp_pagination_render(download_requests)}}</div>

		</div>

        </div>


{% endblock %}

{% block javascripts %}
{{ parent() }}
<script>
$('td').css("vertical-align","middle");
</script>

{% endblock %}

templates/download_request/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New DownloadRequest{% endblock %}

{% block body %}
    <h1>Create new DownloadRequest</h1>

    {{ include('download_request/_form.html.twig') }}

    <a href="{{ path('download_request_index') }}">back to list</a>
{% endblock %}

templates/download_request/rejected.html.twig
{% extends 'base.html.twig' %}
{% block pageheader %}
	<h2> Rejected requests</h2>
{% endblock %}

{% block body %}


</tbody>
</table>

<div class="table-responsive">
			 <table class="table table-bordered table-condensed">
				<thead>
					<tr>
						<th>#</th>
						<th>FullNames</th>
						<th>Email</th>

						<th>Request Reason</th>
						<th>Rejection Message</th>
						<th>Restricted</th>
						<th>Legitimacy File</th>
						<th>RequestedDate</th>
						{# <th>Directorate</th>
						<th>NDMC</th>
						<th>Department</th>
						<th>actions</th> #}
					</tr>
				</thead>
				<tbody>
					{% set id = 1 %}
					{% for download_request in download_requests %}
						<tr style="vertical-align:middle">
							<td  >{{ id }}
								{% set id = id+1  %}</td>
							<td >{{ download_request.Name }}
								{{ download_request.MiddleName }}
								{{ download_request.LastName }}</td>
							<td >{{ download_request.Email }}</td>

							<td >{{ download_request.Reason|raw }}</td>
							<td >{{ download_request.rejectionMessage|raw }}</td>

							<td >
								{% if download_request.dataset.isRestricted %}
									<p class="badge badge-danger">Yes</p>
									<p>
										<form method="post" class="inline" action="{{ path('download_restriction') }}" class="form-inline">
											<input name="restriction" value="{{ download_request.id}}" hidden/>
											<button class="btn btn-sm btn-success inline" type="submit">
												<i class="fa fa-download"></i>
												download</button>


										</form>

									</p>

								{% else %}
									<span class="badge badge-success">Not Restricted</span>
								{% endif %}

							</td>

							<td >
								{% if download_request.file %}

									<p>
										<form method="post" class="inline" action="{{ path('download_legitimacy') }}" class="form-inline">
											<input name="legitimacy" value="{{ download_request.id}}" hidden/>
											<button class="btn btn-sm btn-success inline" type="submit">
												<i class="fa fa-download"></i>
												download</button>


										</form>

									</p>


								{% endif %}

							</td>

							<td >{{ download_request.RequestedDate ? download_request.RequestedDate|date('Y-m-d') : '' }}</td>


							{# <td>
								<span class="label label-danger"><i class="fa fa-arrow-right"></i> {{download_request.approver1 }}</span>
							</td>

	<td>
								<span class="label label-danger"><i class="fa fa-arrow-right"></i>{{download_request.approver2 }}</span>
							</td>

							<td >
								<span class="label label-danger"> {{download_request.approver3 }} <i style=" transform: rotate(180deg);" class="fa fa-share"></i></span>
							</td>


							<td >
								{% if is_allowed(app.user,'approver1') or is_allowed(app.user,'approver2') or is_allowed(app.user,'approver3') %}

									<a class="btn btn-sm btn-success" href="{{ path('download_request_show', {'id': download_request.id}) }}">Detail</a>


								{% endif %}
							</td>  #}
						</tr>

						{% set stat = "default" %}

					{% else %}
						<tr>
							<td colspan="15">no records found</td>
						</tr>
	{% endfor %}
				</tbody>
			</table>
		<div class="pull-right">
				{{ knp_pagination_render(download_requests)}}</div>

		</div>

        </div>


{% endblock %}

{% block javascripts %}
{{ parent() }}
<script>
$('td').css("vertical-align","middle");
</script>

{% endblock %}

templates/download_request/show.html.twig
{% extends 'base.html.twig' %}

{% block pageheader %} <a href="{{ path('download_request_index') }}" class="btn btn-sm btn-success">back to list</a>{% endblock %}

{% block body %}
    <h1>Download Request</h1>

    <table class="table">
        <tbody>

            <tr>
                <th>Name</th>
                <td>{{ download_request.Name }} {{ download_request.MiddleName }} {{ download_request.LastName }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ download_request.Email }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ download_request.Phone }}</td>
            </tr>
            <tr>
                <th>Reason</th>
                <td>{{ download_request.Reason }}</td>
            </tr>
            <tr>
                <th>Objective</th>
                <td>{{ download_request.objective }}</td>
            </tr>
            <tr>
                <th>Attachment</th>
                <td>{{ download_request.Attachment ? download_request.Attachment|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Requested Date</th>
                <td>{{ download_request.RequestedDate ? download_request.RequestedDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th colspan="2" class="h3">About Requested dataset</th>

            </tr>
            <tr>
                <th>Dataset label</th>
                <td>{{ download_request.dataset.label }}</td>
            </tr>
            <tr>
                <th>Dataset name</th>
                <td>{{ download_request.dataset.name }}</td>
            </tr>
            <tr>
                <th>Dataset titile</th>
                <td>{{ download_request.dataset.title }}</td>
            </tr>

           {% if download_request.File %}
            <tr>
                <th>More info</th>
                <td><a class="btn btn-success" href="{{ asset( 'uploads/dwn_req/' ~ download_request.File ) }}">Download</a></td>
            </tr>
           {% endif %}
        </tbody>
    </table>

                  {% if is_allowed(app.user,'approver1') or is_allowed(app.user,'approver2') or is_allowed(app.user,'approver3') %}

       <a class="btn btn-sm btn-success" onclick="return confirm('request is going to approve?')" href="{{ path('approve_dataset_download_request', {'id': download_request.id}) }}">approve</a>

<a  class="btn btn-sm btn-danger" id="lpend">Reject</a>
								 <br> <br> <br>
            <div class="fin hidden" >
            <form id="frm" method="post" action="{{ path('reject_dataset_download_request', {'id': download_request.id}) }}">
            <textarea rows="4" cols="50" name= "message"></textarea>
            <a  class="btn btn-danger" id="sbmt" onclick="return confirm('Are you sure you want to reject?')" >Confirm</a>
            </form>
            </div>
                  {% endif %}




{% endblock %}

{% block javascripts %}

   <script>
      $("#lpend").click(function(){
        $(".fin").toggleClass("hidden");
        });
        $("#sbmt").click(function(){
        $("#frm").submit();
        });
   </script>
{% endblock %}